/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.draft;

/**
 *
 * @author Santi Mercado
 */
public class puguide extends javax.swing.JFrame {

    /**
     * Creates new form puguide
     */
    public puguide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        jLabel19.setText("A horizontal slash that will destroy all aliens in its way");

        jLabel21.setText("Will slash from the coords x=0 and a random y location");

        jLabel31.setText("The beam is summoned at a random location of the top-right corner");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setText("POWER UPS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(141, 13, 194, 42);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(35, 93, 0, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/draft/Clock.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 60, 50, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/draft/Ykatana.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 50, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/draft/ewand.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 180, 50, 50);

        jLabel6.setText("Stops time for the enemy for 4 seconds");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 80, 230, 16);

        jLabel7.setText("Summons an energy beam that will travel horizontally ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 560, 320, 16);

        jLabel8.setText("Will slash from the coords y=770 and a random x location");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 440, 340, 16);

        jLabel9.setText("Summons an explosion");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 180, 310, 16);

        jLabel10.setText("The beam is summoned at the coords x=0, y= 450");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 580, 400, 16);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/draft/h.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 230, 50, 50);

        jLabel13.setText("Replenishes one of your missing hearts");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(90, 250, 230, 16);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/draft/Eboost.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 300, 50, 50);

        jLabel11.setText("Boost your movement and shooting speed for 5 seconds");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 320, 330, 16);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/draft/Xkatana.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 350, 50, 50);

        jLabel16.setText("Summons a vertical slash");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(70, 120, 300, 16);

        jLabel17.setText("Will slash from the coords x=545, y=770");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(70, 140, 240, 16);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/draft/puhp.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(20, 410, 50, 50);

        jLabel20.setText("Summons a horizontal slash");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(80, 360, 380, 16);

        jLabel22.setText("Will slash from the coords x=0 and a random y location");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(80, 380, 320, 16);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/draft/lpu.png"))); // NOI18N
        jLabel23.setText("jLabel23");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(20, 480, 50, 50);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/draft/finalpu.png"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(30, 680, 50, 50);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/draft/pufk.png"))); // NOI18N
        jLabel25.setText("jLabel24");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(30, 550, 50, 50);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/draft/up.png"))); // NOI18N
        jLabel26.setText("jLabel24");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(30, 610, 50, 50);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("???");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(90, 700, 48, 16);

        jLabel28.setText("Summons an energy sphere that will travel horizontally ");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(80, 420, 320, 16);

        jLabel29.setText("The explosion is summoned at a random location");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(70, 200, 290, 16);

        jLabel30.setText("Summons an energy beam that will travel diagonally ");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(80, 490, 320, 16);

        jLabel32.setText("The beam is summoned at a random location of the top-right corner");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(80, 510, 400, 16);

        jLabel33.setText("Moves all the aliens 60 units up");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(90, 630, 190, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(puguide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(puguide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(puguide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(puguide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new puguide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
